### ISSUE TITLE
Mod broken with Factorio >= 0.17.56

### ISSUE THREAD

**Issue by luziferius** [DaveMcW/rail-bridge#1]
See
https://forums.factorio.com/viewtopic.php?f=3&t=73150

> All rail bounding boxes are now hardcoded/not moddable. This is to avoid unexpected collision/rail block merging behaviour.

(PS: sorry for the weird title, my keyboard did stupid things…)

**Comment by DaveMcW** [comment]
Thanks, I updated the dependencies to require Factorio < 0.17.56. It does not seem likely this mod will be supported in future Factorio versions.

**Comment by luziferius** [comment]
Probably...
I just raised this issue for a quick notification.

This is the most sensible 'fix', so it is solved from my point of view.
